services:
  app:
    image: yazanzaid00/express-app:latest
    container_name: express-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=express-app"

  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--label-enable"
      - "--scope"
      - "express-app"
      - "--interval"
      - "60"
      - "--cleanup"
      - "--remove-volumes"
